Repository nanten2/necst-ros, pull requests merged in 2022-03, with the labels that each got.

#493 #492 tmpfix
  .gitignore
  lib/dfs_table.py
  simulator/device/S_ROS_oneshot_achilles.py
Labels: bug

#496 Observation base class
  install.sh
  lib/__init__.py
  lib/device/S_antenna_device.py
  lib/device/__init__.py
  lib/device/antenna_az_commander_pid.py
  lib/device/antenna_device.py
  lib/device/antenna_el_commander_pid.py
  lib/device/antenna_pid.py
  lib/device/pid_antenna_device.py
  lib/device/utils/__init__.py
  lib/device/utils/data_utils.py
  lib/device/utils/math_utils.py
  lib/device/utils/quantity_utils.py
  obs_scripts/_observation.py
  poetry.lock
  pyproject.toml
  scripts/device/ROS_antenna_move.py
  scripts/device/ROS_antenna_move_2.py
  simulator/device/S_ROS_antenna_move.py
Labels: enhancement, invalid

#499 Use python3
  lib/azel_to_radec.py
  lib/read_obsfile.py
  logger/scripts/ROS_save_log_db.py
  logger/scripts/weather_server.py
  obs_scripts/ROS_cross_planet.py
  obs_scripts/ROS_cross_point.py
  obs_scripts/ROS_focus_planet.py
  obs_scripts/ROS_opt_cross.py
  obs_scripts/ROS_otf.py
  obs_scripts/ROS_otf_planet.py
  obs_scripts/ROS_otf_tmp.py
  obs_scripts/ROS_ps.py
  obs_scripts/ROS_ps_edge.py
  obs_scripts/ROS_ps_planet.py
  obs_scripts/S_oneshot.py
  obs_scripts/S_opt_point.py
  obs_scripts/cross_planet_xffts.py
  obs_scripts/cross_point_xffts.py
  obs_scripts/cross_point_xffts2.py
  obs_scripts/edge_point_xffts_ac.py
  obs_scripts/finalize.py
  obs_scripts/focus_object_xffts.py
  obs_scripts/focus_planet_xffts.py
  obs_scripts/initialize.py
  obs_scripts/monitor_dfs_power.py
  obs_scripts/moon_point.py
  obs_scripts/onepoint_track.py
  obs_scripts/oneshot_ch.py
  obs_scripts/opt_point.py
  obs_scripts/otf_horizontal_xffts.py
  obs_scripts/otf_planet_xffts.py
  obs_scripts/otf_xffts3.py
  obs_scripts/otf_xffts4.py
  obs_scripts/ps_xffts.py
  obs_scripts/skydip.py
  obs_scripts/skydip_xffts.py
  rx_scripts/allan.py
  rx_scripts/linearity.py
  rx_scripts/linearity_new.py
  scripts/device/ROS_camera.py
  scripts/device/ROS_image.py
  scripts/device/ROS_oneshot_achilles.py
  scripts/device/ROS_smartcounter.py
  scripts/helper/ROS_analy_node.py
  scripts/helper/ROS_obsmode.py
  scripts/helper/ROS_pub_txtfile.py
  scripts/record/ROS_save_wclist.py
  scripts/record/ROS_sub_txtfile.py
  scripts/record/save_weatherlog.py
  scripts/record/save_xffts_data_n2f.py
  simulator/device/S_ROS_image.py
  simulator/test/data_server_dammy.py
Labels: bug, invalid

#500 Create Python packages
  CMakeLists.txt
  necst/__init__.py
  obs_scripts/__init__.py
  poetry.lock
  pyproject.toml
  rx_scripts/__init__.py
  scripts/__init__.py
  setup.py
  simulator/__init__.py
  tests/__init__.py
Labels: invalid

#501 Update PID controller
  .gitignore
  lib/device/__init__.py
  lib/device/antenna_az_commander_pid.py
  lib/device/antenna_device.py
  lib/device/antenna_el_commander_pid.py
  lib/device/antenna_pid.py
  lib/device/utils/__init__.py
  lib/device/utils/data_utils.py
  lib/device/utils/math_utils.py
  lib/device/utils/quantity_utils.py
  poetry.lock
  pyproject.toml
Labels: bug, invalid

#507 Fix error message and default value for status
  Pipfile
  Pipfile.lock
  install.sh
  poetry.lock
  scripts/controller/ROS_controller.py
Labels: bug

#508 #495 first version
  obs_scripts/otf.py
Labels: enhancement
